let movies: any[] = [
  {
    adult: false,
    backdrop_path: '/u7kuUaySqXBVAtqEl9vkTkAzHV9.jpg',
    genre_ids: [18, 35],
    id: 20453,
    original_language: 'hi',
    original_title: '3 Idiots',
    overview:
      'Rascal. Joker. Dreamer. Genius... You\'ve never met a college student quite like "Rancho." From the moment he arrives at India\'s most prestigious university, Rancho\'s outlandish schemes turn the campus upside down—along with the lives of his two newfound best friends. Together, they make life miserable for "Virus," the school’s uptight and heartless dean. But when Rancho catches the eye of the dean\'s daughter, Virus sets his sights on flunking out the "3 idiots" once and for all.',
    popularity: 30.524,
    poster_path: '/66A9MqXOyVFCssoloscw79z8Tew.jpg',
    release_date: '2009-12-23',
    title: '3 Idiots',
    video: false,
    vote_average: 7.992,
    vote_count: 2192,
  },
  {
    adult: false,
    backdrop_path: '/z4k7b66jAHP8sQbEahxss6Ct8BW.jpg',
    genre_ids: [18, 35, 10749],
    id: 61202,
    original_language: 'hi',
    original_title: 'ज़िन्दगी ना मिलेगी दोबारा',
    overview:
      'Three friends who were inseparable in childhood decide to go on a three-week-long bachelor road trip to Spain, in order to re-establish their bond and explore thrilling adventures, before one of them gets married. What will they learn of themselves and each other during the adventure?',
    popularity: 12.82,
    poster_path: '/hKO9O715wYxjkQSEv47giCYcyO8.jpg',
    release_date: '2011-07-15',
    title: 'Zindagi Na Milegi Dobara',
    video: false,
    vote_average: 7.545,
    vote_count: 314,
  },
  {
    adult: false,
    backdrop_path: '/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg',
    genre_ids: [28, 12, 14, 878],
    id: 19995,
    original_language: 'en',
    original_title: 'Avatar',
    overview:
      'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
    popularity: 123.153,
    poster_path: '/kyeqWdyUXW608qlYkRqosgbbJyK.jpg',
    release_date: '2009-12-15',
    title: 'Avatar',
    video: false,
    vote_average: 7.6,
    vote_count: 30081,
  },
  {
    adult: false,
    backdrop_path: '/pzgzH4LJoFmQKVPgKs0VZPWUoFZ.jpg',
    genre_ids: [18],
    id: 1096978,
    original_language: 'es',
    original_title: 'Avatar',
    overview:
      'Tension mounts between a quadraplegic man and his wife as she prepares a bath for him.',
    popularity: 3.099,
    poster_path: '/gmnD2e1RvMdCl9D1rsDEQaQlJxK.jpg',
    release_date: '2006-04-11',
    title: 'Avatar',
    video: false,
    vote_average: 6,
    vote_count: 23,
  },
  {
    adult: false,
    backdrop_path: '/8rpDcsfLJypbO6vREc0547VKqEv.jpg',
    genre_ids: [878, 12, 28],
    id: 76600,
    original_language: 'en',
    original_title: 'Avatar: The Way of Water',
    overview:
      'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
    popularity: 301.686,
    poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    release_date: '2022-12-14',
    title: 'Avatar: The Way of Water',
    video: false,
    vote_average: 7.65,
    vote_count: 10281,
  },
  {
    adult: false,
    backdrop_path: '/uEwGFGtao9YG2JolmdvtHLLVbA9.jpg',
    genre_ids: [99],
    id: 111332,
    original_language: 'en',
    original_title: 'Avatar: Creating the World of Pandora',
    overview:
      "The Making-of James Cameron's Avatar. It shows interesting parts of the work on the set.",
    popularity: 11.023,
    poster_path: '/d9oqcfeCyc3zmMal6eJbfj3gatc.jpg',
    release_date: '2010-02-07',
    title: 'Avatar: Creating the World of Pandora',
    video: false,
    vote_average: 6.8,
    vote_count: 125,
  },
  {
    adult: false,
    backdrop_path: '/fCK2T5ruQrqRsciJ01jjQSkNWVq.jpg',
    genre_ids: [16, 28, 12, 14],
    id: 613200,
    original_language: 'zh',
    original_title: '全职高手之巅峰荣耀',
    overview:
      "In this prequel to the animated series The King's Avatar, Ye Xiu enters into the pro gaming world of Glory, and competes in the first Pro League series tournament.",
    popularity: 6.669,
    poster_path: '/6lyXW6GC7ruwDmhvEcRd9d46ZO7.jpg',
    release_date: '2019-08-16',
    title: "The King's Avatar: For the Glory",
    video: false,
    vote_average: 7,
    vote_count: 37,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [35],
    id: 926519,
    original_language: 'fr',
    original_title: "L'Avatar botanique de mademoiselle Flora",
    overview:
      'A young woman lives sadly in a small garrison town with a soldier. Little by little, won over by boredom, sadness, total inaction, she develops a relationship with plants and starts talking to plants.',
    popularity: 1.218,
    poster_path: '/jV7LWoQbwXplgdIbMvT4UB8O1E3.jpg',
    release_date: '1965-05-05',
    title: 'The Botanical Avatar of Mademoiselle Flora',
    video: false,
    vote_average: 6.8,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: '/eoAvHxfbaPOcfiQyjqypWIXWxDr.jpg',
    genre_ids: [99],
    id: 1059673,
    original_language: 'en',
    original_title: 'Avatar: The Deep Dive - A Special Edition of 20/20',
    overview:
      'An inside look at one of the most anticipated movie sequels ever with James Cameron and cast.',
    popularity: 20.801,
    poster_path: '/rtVeIsmeXnpjNbEKnm9Say58XjV.jpg',
    release_date: '2022-12-14',
    title: 'Avatar: The Deep Dive - A Special Edition of 20/20',
    video: false,
    vote_average: 7.333,
    vote_count: 60,
  },
  {
    adult: false,
    backdrop_path: '/agnESua8QxISkOERvs7td6BAesa.jpg',
    genre_ids: [28, 18, 878],
    id: 1092060,
    original_language: 'ja',
    original_title: '暴太郎戦隊ドンブラザーズVSゼンカイジャー',
    overview: '',
    popularity: 7.777,
    poster_path: '/h5MwCuYy2EUv3AmD3d3E6AUYo90.jpg',
    release_date: '2023-05-03',
    title: 'Avataro Sentai Donbrothers vs. Zenkaiger',
    video: false,
    vote_average: 5.6,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [28, 878, 12],
    id: 83533,
    original_language: 'en',
    original_title: 'Avatar 3',
    overview: 'The third entry in the Avatar franchise.',
    popularity: 14.498,
    poster_path: '/eZXoA5BjUxm1fdAKb3lPvbDY2L8.jpg',
    release_date: '2025-12-17',
    title: 'Avatar 3',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 1132450,
    original_language: 'ja',
    original_title: '暴太郎戦隊ドンブラザーズVS暴太郎戦隊ドンブリーズ',
    overview:
      "The Avataro Sentai Donburies, which first appeared in Avataro Sentai Donbrothers' press conference gets a TTFC special!",
    popularity: 1.195,
    poster_path: '/9hiiML3NMC4Qj25V97XEYl7bVKw.jpg',
    release_date: '2023-11-05',
    title: 'Avataro Sentai Donbrothers vs. Avataro Sentai Donburies',
    video: false,
    vote_average: 10,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99, 878],
    id: 100287,
    original_language: 'da',
    original_title: 'Min Avatar og mig',
    overview:
      'is a creative documentary-fiction film and a film that might expand your sense of reality. It is the story about a man who enters the virtual world Second Life to pursue his personal dreams and ambitions. His journey into cyberspace becomes a magic learning experience, which gradually opens the gates to a much larger reality.',
    popularity: 1.014,
    poster_path: '/dZCj0jiOoDzAzbQM7ryYFEjkjs7.jpg',
    release_date: '2010-11-10',
    title: 'My Avatar and Me',
    video: false,
    vote_average: 6.357,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [28, 878, 12, 14, 53],
    id: 216527,
    original_language: 'en',
    original_title: 'Avatar 4',
    overview: '',
    popularity: 10.283,
    poster_path: '/xGcd3ob2DWC3TmlVhnJg1RLyTGi.jpg',
    release_date: '2029-12-20',
    title: 'Avatar 4',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 829860,
    original_language: 'zh',
    original_title: "Hunan, l'autre monde d'Avatar",
    overview:
      "How China's magical Zhangjiajie National Park attracted director James Cameron, who came seeking inspiration for a mysterious fictional planet.",
    popularity: 1.176,
    poster_path: '/aCwF72gto2ADsQK28j7S9tE4xDa.jpg',
    release_date: '2015-01-01',
    title: 'Hunan: The Other World of Avatar',
    video: false,
    vote_average: 7.2,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: '/axSaeKvV5xF3zGYwXaSF8rUxaO1.jpg',
    genre_ids: [99],
    id: 183392,
    original_language: 'en',
    original_title: 'Capturing Avatar',
    overview:
      "Capturing Avatar is a feature length behind-the-scenes documentary about the making of Avatar. It uses footage from the film's development, as well as stock footage from as far back as the production of Titanic in 1995. Also included are numerous interviews with cast, artists, and other crew members. The documentary was released as a bonus feature on the extended collector's edition of Avatar.",
    popularity: 10.541,
    poster_path: '/26SMEXJl3978dn2svWBSqHbLl5U.jpg',
    release_date: '2010-11-16',
    title: 'Capturing Avatar',
    video: false,
    vote_average: 7.39,
    vote_count: 73,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [28, 12, 878],
    id: 393209,
    original_language: 'en',
    original_title: 'Avatar 5',
    overview: '',
    popularity: 10.361,
    poster_path: '/vAvLQOyFoire5x8AmRNfvgkvrMZ.jpg',
    release_date: '2031-12-18',
    title: 'Avatar 5',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/1T4sqygTH5SYzU5DtmI5K9ep2eP.jpg',
    genre_ids: [28, 12, 14, 878],
    id: 937315,
    original_language: 'ja',
    original_title: '暴太郎戦隊ドンブラザーズ THE MOVIE 新・初恋ヒーロー',
    overview: '',
    popularity: 5.68,
    poster_path: '/8MacEBNLdMnmroPAx6LNmi6oJaj.jpg',
    release_date: '2022-07-22',
    title: 'Avataro Sentai Donbrothers The Movie: New First Love Hero',
    video: false,
    vote_average: 7.2,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: '/gO81IsgrhwUS6aChXCjnjFKUS3S.jpg',
    genre_ids: [27],
    id: 282908,
    original_language: 'ja',
    original_title: 'アバター',
    overview:
      'Michiko lost her dad in a car accident when she was 10 years old. After the car accident, Michiko has lived with her mother Kyoko. Michiko, now in her 2nd year of high school, gets a cell phone from her mother as a birthday present. Michiko is so excited to have her very first cell phone. Soon afterwards, she is forced into joining social networking site "AvaQ" by classmate, and queen of the classroom, Taeko.',
    popularity: 3.207,
    poster_path: '/xEAhV18F5Ej78qL0EneyPqa2a20.jpg',
    release_date: '2011-04-30',
    title: 'Avatar',
    video: false,
    vote_average: 5.875,
    vote_count: 12,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 287003,
    original_language: 'en',
    original_title: 'Avatar: Scene Deconstruction',
    overview: 'The deconstruction of the Avatar scenes and sets',
    popularity: 6.162,
    poster_path: '/uCreCQFReeF0RiIXkQypRYHwikx.jpg',
    release_date: '2009-12-18',
    title: 'Avatar: Scene Deconstruction',
    video: false,
    vote_average: 6.709,
    vote_count: 43,
  },
  {
    adult: false,
    backdrop_path: '/wEjFjWu5yiHk6U5YV9kSnwdWwNO.jpg',
    genre_ids: [53, 14, 27],
    id: 677528,
    original_language: 'kn',
    original_title: 'ಅವತಾರ ಪುರುಷ: Part 1',
    overview:
      "When a son of an Ayurveda scholar goes missing, he blames his sister and cuts all ties with her. When the latter's daughter decides to set things right with a devious plan, there seems to be more trouble waiting for the family.",
    popularity: 4.114,
    poster_path: '/gQ29E9Qy6z5ExsxnpgUTHfpZFO3.jpg',
    release_date: '2022-05-06',
    title: 'Avatara Purusha: Part 1',
    video: false,
    vote_average: 5.455,
    vote_count: 11,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 278698,
    original_language: 'en',
    original_title: 'Avatar Spirits',
    overview:
      'Bryan Konietzko and Michael Dante DiMartino, co-creators of the hit television series, Avatar: The Last Airbender, reflect on the creation of the masterful series.',
    popularity: 5.746,
    poster_path: '/oBWVyOdntLJd5bBpE0wkpN6B6vy.jpg',
    release_date: '2010-06-22',
    title: 'Avatar Spirits',
    video: false,
    vote_average: 7.944,
    vote_count: 27,
  },
  {
    adult: false,
    backdrop_path: '/nlCHUWjY9XWbuEUQauCBgnY8ymF.jpg',
    genre_ids: [28, 12, 878],
    id: 76341,
    original_language: 'en',
    original_title: 'Mad Max: Fury Road',
    overview:
      'An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order.',
    popularity: 212.305,
    poster_path: '/hA2ple9q4qnwxp3hKVNhroipsir.jpg',
    release_date: '2015-05-13',
    title: 'Mad Max: Fury Road',
    video: false,
    vote_average: 7.585,
    vote_count: 21112,
  },
  {
    adult: false,
    backdrop_path: '/mWQg2INejtX1PCWRAN4vseadA6H.jpg',
    genre_ids: [12, 28, 53, 878],
    id: 9659,
    original_language: 'en',
    original_title: 'Mad Max',
    overview:
      "In the ravaged near future, a savage motorcycle gang rules the road. Terrorizing innocent civilians while tearing up the streets, the ruthless gang laughs in the face of a police force hell-bent on stopping them. But they underestimate one officer: Max Rockatansky. And when the bikers brutalize Max's best friend and family, they send him into a mad frenzy that leaves him with only one thing left in the world to live for – revenge!",
    popularity: 43.011,
    poster_path: '/5LrI4GiCSrChgkdskVZiwv643Kg.jpg',
    release_date: '1979-04-12',
    title: 'Mad Max',
    video: false,
    vote_average: 6.686,
    vote_count: 3959,
  },
  {
    adult: false,
    backdrop_path: '/jEuwsmFS8JPzkDIhRL3B2BVYbU4.jpg',
    genre_ids: [12, 28, 53, 878],
    id: 8810,
    original_language: 'en',
    original_title: 'Mad Max 2',
    overview:
      'Max Rockatansky returns as the heroic loner who drives the dusty roads of a postapocalyptic Australian Outback in an unending search for gasoline. Arrayed against him and the other scraggly defendants of a fuel-depot encampment are the bizarre warriors commanded by the charismatic Lord Humungus, a violent leader whose scruples are as barren as the surrounding landscape.',
    popularity: 47.921,
    poster_path: '/dhVekfpaCW3QavAwGYbaQig87Xc.jpg',
    release_date: '1981-12-24',
    title: 'Mad Max 2',
    video: false,
    vote_average: 7.387,
    vote_count: 3342,
  },
  {
    adult: false,
    backdrop_path: '/84j84SdeQRJqeNnqkKKExeiUAgW.jpg',
    genre_ids: [28, 878, 53],
    id: 786892,
    original_language: 'en',
    original_title: 'Furiosa: A Mad Max Saga',
    overview:
      'As the world falls, young Furiosa is snatched from the Green Place of Many Mothers into the hands of a great biker horde led by the warlord Dementus. Sweeping through the wasteland, they encounter the citadel presided over by Immortan Joe. The two tyrants wage war for dominance, and Furiosa must survive many trials as she puts together the means to find her way home.',
    popularity: 98.151,
    poster_path: '/pKaA8VvfkNfEMUPMiiuL5qSPQYy.jpg',
    release_date: '2024-05-22',
    title: 'Furiosa: A Mad Max Saga',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/br1zDvgmBPa1EbBrUmEDaXXgykq.jpg',
    genre_ids: [28, 12, 878],
    id: 9355,
    original_language: 'en',
    original_title: 'Mad Max Beyond Thunderdome',
    overview:
      'Mad Max becomes a pawn in a decadent oasis of a technological society, and when exiled, becomes the deliverer of a colony of children.',
    popularity: 36.815,
    poster_path: '/jJlxcEVVUHnrUeEkQ0077VeHQpb.jpg',
    release_date: '1985-06-29',
    title: 'Mad Max Beyond Thunderdome',
    video: false,
    vote_average: 6.196,
    vote_count: 2581,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 1150126,
    original_language: 'en',
    original_title: 'Mad Max Exposed',
    overview:
      'Step into the world of the original Mad Max movie and take a rare behind the scenes look at the making of this groundbreaking film.',
    popularity: 1.036,
    poster_path: '/seyD0wElKtESdRf4PKthA64WnTl.jpg',
    release_date: '2022-06-01',
    title: 'Mad Max Exposed',
    video: false,
    vote_average: 7,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [28, 12, 878],
    id: 340023,
    original_language: 'en',
    original_title: 'Mad Max: The Wasteland',
    overview: 'Sequel to the film "Mad Max: Fury Road"',
    popularity: 8.297,
    poster_path: '/4S2ruDG18iwWgnBNn7q9yByXwTw.jpg',
    release_date: '',
    title: 'Mad Max: The Wasteland',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 692281,
    original_language: 'pt',
    original_title: 'Mad.Max',
    overview: '',
    popularity: 1.952,
    poster_path: '/4fbUAemJ75HuJ1MCSUnadG6212H.jpg',
    release_date: '',
    title: 'Mad.Max',
    video: true,
    vote_average: 9.5,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [28, 12, 878, 53],
    id: 307732,
    original_language: 'en',
    original_title: 'Mad Max: Renegade',
    overview:
      'Mad Max Renegade follows the further adventures of Max Rockatansky after his desertion from Main Force Patrol in his famed Pursuit Special, more commonly known as the Interceptor.',
    popularity: 3.145,
    poster_path: '/tKSLSe5ZhcCHMNWyfsmH8D3WykZ.jpg',
    release_date: '2011-12-03',
    title: 'Mad Max: Renegade',
    video: false,
    vote_average: 5.9,
    vote_count: 18,
  },
  {
    adult: false,
    backdrop_path: '/dSnrVpDOoYxxBjyb44eE8XX5eEJ.jpg',
    genre_ids: [35],
    id: 554247,
    original_language: 'en',
    original_title: 'Mad Maxine: Frisky Road',
    overview:
      'In a post-apocalyptic wasteland, the Bone Warrior Mad Maxine travels the desert highways for fashion accessories to soothe her broken heart.  Many will try to stop her, and many will fail. But the sexual roadblocks of a g-stringed biker gang and evil dictator Immortan Hoe may ultimately prove more tempting than a 30 percent discount on Christian Louboutin pumps.',
    popularity: 1.432,
    poster_path: '/sSnQmoIqUuPcso3tcE53nPwDJ4.jpg',
    release_date: '2018-10-08',
    title: 'Mad Maxine: Frisky Road',
    video: false,
    vote_average: 3,
    vote_count: 4,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 650738,
    original_language: 'en',
    original_title: 'Mad to The Max: Hoon Nation',
    overview: 'A look at Aussies Hoodlum culture.',
    popularity: 0.6,
    poster_path: '/pxcpLk7sYk7a1G3w2S1IOAAVzP6.jpg',
    release_date: '2017-11-01',
    title: 'Mad to The Max: Hoon Nation',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [28, 12, 878],
    id: 340266,
    original_language: 'fr',
    original_title: 'Mad Max a Wasteland Story',
    overview: '',
    popularity: 0.84,
    poster_path: null,
    release_date: '2012-10-23',
    title: 'Mad Max a Wasteland Story',
    video: false,
    vote_average: 7.2,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: '/6PCprqrm0kdzYdAtZlSiFoY0Ypi.jpg',
    genre_ids: [28, 16],
    id: 95414,
    original_language: 'en',
    original_title: 'Superman',
    overview:
      'After The Daily Planet receives a letter from a mad scientist threatening to wreak destruction with his Electrothanasia Ray, Lois Lane heads out in the hopes of getting more information for a news story.',
    popularity: 8.246,
    poster_path: '/be4a0lyJF3Jo9Z1ykVR7gYUfBQt.jpg',
    release_date: '1941-09-26',
    title: 'Superman',
    video: false,
    vote_average: 6.9,
    vote_count: 84,
  },
  {
    adult: false,
    backdrop_path: '/x4vEAadf8Z5s7GJhUdNvzfVa7zo.jpg',
    genre_ids: [28, 878],
    id: 30927,
    original_language: 'en',
    original_title: 'Stryker',
    overview:
      'The world\'s water supply has dried up due to some sort of apocalypse. A beautiful woman holds the secret to where one of the last springs being guarded by a group of Amazons. A "Road Warrior" like crew captures her and tries to make her talk through brutal torture. The hero (Stryker) unites with some of the remaining "good guys" and the Amazons and frees the woman. They go on to a "Road Warrior" type of concluding battle with the bad guys.',
    popularity: 3.395,
    poster_path: '/bi70VjACRZExyfdvNesSibuByXi.jpg',
    release_date: '1983-09-02',
    title: 'Stryker',
    video: false,
    vote_average: 3.868,
    vote_count: 19,
  },
  {
    adult: false,
    backdrop_path: '/dZrZN18EylSnz55r8gTGmChAcHm.jpg',
    genre_ids: [18, 10749, 10752],
    id: 547028,
    original_language: 'en',
    original_title: 'The Mad Empress',
    overview:
      'The Mad Empress is a 1939 American historical drama film depicting the 3-year reign of Maximilian I of Mexico and his struggles against Benito Juarez.',
    popularity: 1.359,
    poster_path: '/qq1UzeQtiJNA6mrvrQ7fCcrD120.jpg',
    release_date: '1939-12-16',
    title: 'The Mad Empress',
    video: false,
    vote_average: 5.8,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: '/tR0UcJ45V4Ij310zyNrQOsYEPBe.jpg',
    genre_ids: [12, 28],
    id: 257723,
    original_language: 'tr',
    original_title: 'Ölüme Son Adım',
    overview:
      "Ultra hardcore mercenary Kaan, the kind of guy who carries an astonishing amount of large knives on his body at all times, is hired by some guy in a suit with a nervous tic (Patron) to rescue a Professor who has found the cure for leukaemia from some unnamed and unexplained heavily armed evildoers holding him somewhere out in the country. Tic guy is willing to pay Kaan 100 million TL for his efforts, so there's no reason for the mercenary not to take the offer...",
    popularity: 0.84,
    poster_path: '/kMreVhr8jBVZjeD2s1zFShOx8AR.jpg',
    release_date: '1983-01-01',
    title: 'Last Step to Death',
    video: false,
    vote_average: 3.4,
    vote_count: 5,
  },

  {
    adult: false,
    backdrop_path: null,
    genre_ids: [35],
    id: 15411,
    original_language: 'hi',
    original_title: 'भेजा फ्राई',
    overview:
      "Ranjeet Thadani (Rajat Kapoor), a bored, arrogant music company executive hurts his back the night he has found a prize catch for a weekly bring - your -idiot talent dinner hosted by his friends and him. He ends up spending the evening with this idiot, Bharat Bhushan (Vinay Pathak) who tries to help him get his wife (Sarika) back who left him earlier that day. The result is utter chaos let loose by the idiot, who cannot do a single thing without messing it up further. The plot turns around to be a series of mini disasters that leave Ranjeet's comfortable life in ruins. Call it the idiot's revenge!",
    popularity: 2.693,
    poster_path: '/2Wqlcf63EvabGzVffPppfpWlx2B.jpg',
    release_date: '2007-04-13',
    title: 'Bheja Fry',
    video: false,
    vote_average: 6.646,
    vote_count: 41,
  },

  {
    adult: false,
    backdrop_path: '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    genre_ids: [18, 80],
    id: 278,
    original_language: 'en',
    original_title: 'The Shawshank Redemption',
    overview:
      'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
    popularity: 259.23,
    poster_path: '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    release_date: '1994-09-23',
    title: 'The Shawshank Redemption',
    video: false,
    vote_average: 8.706,
    vote_count: 25045,
  },
  {
    adult: false,
    backdrop_path: '/u6hgtSIzW8nDKKWmun9JDhZz2fp.jpg',
    genre_ids: [99],
    id: 546312,
    original_language: 'en',
    original_title: 'Shawshank: The Redeeming Feature',
    overview:
      'Film critic and presenter Mark Kermode explores the fascination and praise audiences, fans and critics have behind the classic The Shawshank Redemption (1994) and how its importance grew higher over the years despite being an overlooked film when it was released and not getting any Oscars victories when it was nominated as one of the Best Pictures of the Year.',
    popularity: 2.143,
    poster_path: '/b7DGM74MRfiLqEveVKwh0jnQ8zX.jpg',
    release_date: '2001-09-08',
    title: 'Shawshank: The Redeeming Feature',
    video: false,
    vote_average: 8.7,
    vote_count: 14,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 897459,
    original_language: 'en',
    original_title:
      'Hope Springs Eternal: A Look Back at The Shawshank Redemption',
    overview: 'Documentary about the movie.',
    popularity: 1.301,
    poster_path: '/v4wcS8XwUn5zl57rYRMzMnKahmt.jpg',
    release_date: '2004-06-25',
    title: 'Hope Springs Eternal: A Look Back at The Shawshank Redemption',
    video: false,
    vote_average: 7.7,
    vote_count: 3,
  },

  {
    adult: false,
    backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    genre_ids: [18, 80],
    id: 238,
    original_language: 'en',
    original_title: 'The Godfather',
    overview:
      'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
    popularity: 123.932,
    poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    release_date: '1972-03-14',
    title: 'The Godfather',
    video: false,
    vote_average: 8.708,
    vote_count: 19058,
  },
  {
    adult: false,
    backdrop_path: '/jdbN2hW8NOaJfDVuMIfF3c1dsQ4.jpg',
    genre_ids: [99, 10402],
    id: 1154878,
    original_language: 'ja',
    original_title: 'JAZZ GODFATHER',
    overview: '',
    popularity: 1.194,
    poster_path: '/4CDjK8m5gmBkAzHzvyi6TmIo2P5.jpg',
    release_date: '2023-11-11',
    title: 'Jazz Godfather',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/9jzcBj3K3sOJe1yF73JEFPISIHE.jpg',
    genre_ids: [80, 18, 53],
    id: 242,
    original_language: 'en',
    original_title: 'The Godfather Part III',
    overview:
      'In the midst of trying to legitimize his business dealings in 1979 New York and Italy, aging mafia don, Michael Corleone seeks forgiveness for his sins while taking a young protege under his wing.',
    popularity: 60.122,
    poster_path: '/lm3pQ2QoQ16pextRsmnUbG2onES.jpg',
    release_date: '1990-12-25',
    title: 'The Godfather Part III',
    video: false,
    vote_average: 7.424,
    vote_count: 5718,
  },
  {
    adult: false,
    backdrop_path: '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
    genre_ids: [18, 80],
    id: 240,
    original_language: 'en',
    original_title: 'The Godfather Part II',
    overview:
      'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
    popularity: 75.49,
    poster_path: '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
    release_date: '1974-12-20',
    title: 'The Godfather Part II',
    video: false,
    vote_average: 8.59,
    vote_count: 11501,
  },
  {
    adult: false,
    backdrop_path: '/nIiSCZvxDeCeXrOJnpbmRB8FcKH.jpg',
    genre_ids: [28, 80, 18],
    id: 79026,
    original_language: 'en',
    original_title: 'El padrino',
    overview:
      'In the streets of East Los Angeles, Manny is a formidable drug dealer. Impressed by his extravagant lifestyle and prowess, his young son, Kilo, yearns to follow in his footsteps. Kilo resolves to learn how to prosper in the drug world, and his new life as a dealer begins. In a world where a man wants everything, he may end up with nothing.',
    popularity: 6.895,
    poster_path: '/10J7EQ8WvMYku8lcZrLewV2Ko4I.jpg',
    release_date: '2004-09-27',
    title: 'El padrino: The Latin Godfather',
    video: false,
    vote_average: 6.9,
    vote_count: 33,
  },
  {
    adult: false,
    backdrop_path: '/fE0Xmb0GaAm1R5NkrMuPezjoGwS.jpg',
    genre_ids: [35, 80, 10749],
    id: 70829,
    original_language: 'ko',
    original_title: 'The Last Godfather',
    overview:
      "Young-goo the son of mafia boss Don Carini, is too foolish to be part of the mafia elite. One day, Young-goo comes to his father and is trained by Tony V to be his father's successor. A few days later, Young-goo accidentally rescues Nancy, the only daughter of Don Bonfante, the boss of a rival mafia family. But Vinnie, an under-boss of the Bonfante family kidnapped her and fabricates that Young-goo has taken her. Vinnie's behavior provokes an armed conflict between the two families.",
    popularity: 3.462,
    poster_path: '/zLcKGxKn8qgrGaUZAWZY3Nvi5fr.jpg',
    release_date: '2010-12-29',
    title: 'The Last Godfather',
    video: false,
    vote_average: 4.731,
    vote_count: 13,
  },
  {
    adult: false,
    backdrop_path: '/nMZ2hUyw8PXT4a1Nbhzr9LX95ie.jpg',
    genre_ids: [28, 18],
    id: 863931,
    original_language: 'te',
    original_title: 'గాడ్‌ఫాదర్‌',
    overview:
      'The sudden demise of the celebrated leader PKR leaves the ruling party in a political crisis and shakes up the family. The party has to elect a leader, and more than one player is in contention. Everyone’s intentions are blurred, and loyalties are in question. Brahma is a game changer in this squabble. Who will succeed as the leader and become the CM?',
    popularity: 3.605,
    poster_path: '/im4u5huiePz0PKFWF4Thb7Tc3db.jpg',
    release_date: '2022-10-05',
    title: 'GodFather',
    video: false,
    vote_average: 5.2,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: '/jVBGqeD1IUXnc6cIJZleKdX6jOg.jpg',
    genre_ids: [28, 80, 18],
    id: 107641,
    original_language: 'ja',
    original_title: '鬼龍院花子の生涯',
    overview:
      'Onimasa is the egocentric boss of a small yakuza clan on Shikoku Island, whose criminal duties conflict with his self-image as a chivalrous samurai. His struggles with his boss, the Shikoku Godfather, and the tumultuous life of his adopted daughter, Matsue, form the backdrop of this epic tale of justice, obedience, and bloody vengeance.',
    popularity: 3.572,
    poster_path: '/vGP9WAxhXFTtEmoemhy3ysIwLkT.jpg',
    release_date: '1982-06-05',
    title: 'Onimasa: A Japanese Godfather',
    video: false,
    vote_average: 6.3,
    vote_count: 19,
  },
  {
    adult: false,
    backdrop_path: '/e4S1jhTMXJRjhG1S8doUW81DH2i.jpg',
    genre_ids: [16, 18, 35],
    id: 13398,
    original_language: 'ja',
    original_title: '東京ゴッドファーザーズ',
    overview:
      'On Christmas Eve, three homeless people living on the streets of Tokyo discover a newborn baby among the trash and set out to find its parents.',
    popularity: 15.903,
    poster_path: '/sPC66btzQlzuRdPKiSDYZ5Hvxgc.jpg',
    release_date: '2003-12-29',
    title: 'Tokyo Godfathers',
    video: false,
    vote_average: 7.894,
    vote_count: 1091,
  },
  {
    adult: false,
    backdrop_path: '/gkfjclGZef5PS8Xm5c7XfZPCxdW.jpg',
    genre_ids: [99, 36],
    id: 598065,
    original_language: 'en',
    original_title: 'Our Godfather',
    overview:
      'The story of how Sicilian Mafia boss Tommaso Buscetta (1928-2000), the Godfather of Two Worlds, revealed, starting in 1984, the deepest secrets of the organization, thus helping to convict the hundreds of mafiosi who were tried in the trial held in Palermo between 1986 and 1987.',
    popularity: 8.214,
    poster_path: '/dSI9Gy5xqmObmKoR9D80Bl0c1GC.jpg',
    release_date: '2019-04-28',
    title: 'Our Godfather',
    video: false,
    vote_average: 6.467,
    vote_count: 61,
  },
  {
    adult: false,
    backdrop_path: '/tXX0mG4yHl3Z0KqPfAxjPOBolGV.jpg',
    genre_ids: [18, 35, 10749],
    id: 134474,
    original_language: 'ml',
    original_title: 'ഗോഡ്ഫാദർ',
    overview:
      'A retelling of William Shakespeare\'s "Romeo and Juliet", the film revolves around the rivalry between two families, the Anjooran and Anappara houses, and the consequences faced when two members of the families fall in love.',
    popularity: 2.837,
    poster_path: '/xnsLPhy3IkgDFDZQjLofOgPDa5d.jpg',
    release_date: '1991-09-15',
    title: 'Godfather',
    video: false,
    vote_average: 7.6,
    vote_count: 27,
  },
  {
    adult: false,
    backdrop_path: '/zmZL53JEoZG32zarRZdE9L7vGqo.jpg',
    genre_ids: [28],
    id: 112587,
    original_language: 'zh',
    original_title: '香港小教父',
    overview:
      'Bruce Liang plays a Chinese Kung Fu movie star, who during his free time carries on a one-man crusade against drug dealers. The villains trick Liang into signing up to appear in a new martial arts movie. The plan is to kill Our Hero while the cameras are running, and make it look like an accident.',
    popularity: 1.803,
    poster_path: '/1ieXvvdaEmvtxXL8dYUKvFymYZD.jpg',
    release_date: '1974-06-28',
    title: 'Little Godfather from Hong Kong',
    video: false,
    vote_average: 7,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: '/tYjyk4Ij7CwVOn2ovcXdRYffR9k.jpg',
    genre_ids: [80, 18],
    id: 364150,
    original_language: 'en',
    original_title: 'The Godfather Epic: 1901-1959',
    overview:
      'The multigenerational saga of the rise and fall of the Corleone crime family. Story is told in chronological order, and numerous scenes that were deleted from each film have been restored.',
    popularity: 10.289,
    poster_path: '/xvT9RyO9UdNSc1NRhXnhTujlQWK.jpg',
    release_date: '1992-10-17',
    title: 'The Godfather Epic: 1901-1959',
    video: true,
    vote_average: 8.9,
    vote_count: 146,
  },
  {
    adult: false,
    backdrop_path: '/AiucbIvr8xSKWxqE8aMkytjxGzM.jpg',
    genre_ids: [80, 18],
    id: 255087,
    original_language: 'ja',
    original_title: '日本の首領 野望篇',
    overview:
      'An ambitious Kansai yakuza don moves in on Tokyo using financial and political tactics, sparking conflict with a local criminal association.',
    popularity: 1.944,
    poster_path: '/dmWtExCufVwBoDHI2E4428ot9OF.jpg',
    release_date: '1977-10-29',
    title: 'Japanese Godfather: Ambition',
    video: false,
    vote_average: 10,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: '/7oonURUE9oDWGX2bjYjj680Bp5R.jpg',
    genre_ids: [28, 35, 80],
    id: 77403,
    original_language: 'en',
    original_title: 'Disco Godfather',
    overview:
      'Retired cop and celebrity DJ Tucker Williams (aka The Disco Godfather) takes to the streets as a dangerous hallucinogenic drug called Angel Dust begins to take hold of the neighborhood.',
    popularity: 5.382,
    poster_path: '/tjHQ0VD4qnb4TFsJlt1MC6hf7V6.jpg',
    release_date: '1979-09-04',
    title: 'Disco Godfather',
    video: false,
    vote_average: 5.74,
    vote_count: 26,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 1093042,
    original_language: 'or',
    original_title: 'ଗଡ୍‌ଫାଦର୍',
    overview: 'to be added later',
    popularity: 0.6,
    poster_path: null,
    release_date: '',
    title: 'Godfather',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [18, 80],
    id: 537395,
    original_language: 'ja',
    original_title: '日本の首領 完結篇',
    overview:
      'The three-film saga comes to a conclusion as three leaders of the underworld battle it out to determine who will become Don of Japan.',
    popularity: 2.881,
    poster_path: '/krQkj0Os90kAg0ZlS09F2Tvt3ZB.jpg',
    release_date: '1978-09-09',
    title: 'Japanese Godfather: Conclusion',
    video: false,
    vote_average: 7,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: '/ej4Yk9TIS6XfGBhNNUgkN8fkRu7.jpg',
    genre_ids: [80, 53],
    id: 262901,
    original_language: 'cs',
    original_title: 'Příběh kmotra',
    overview:
      "Godfather's story is the story of the greatest of Czech post-revolutionary 'entrepreneurs'. His activities often crossed the edge of the law, and his life ended bullet assassin.",
    popularity: 2.444,
    poster_path: '/bdKTLFi4DAKzd95paCqGvk77Ymq.jpg',
    release_date: '2013-10-24',
    title: "Godfather's Story",
    video: false,
    vote_average: 6,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [35],
    id: 260889,
    original_language: 'it',
    original_title: "L'altra faccia del padrino",
    overview:
      'The Godfather Don Vito Monreale knows, by chance, the Italian-American singer Nick Bouillon. Since the two are alike, Don Vito decided to exploit this similarity in his favour.',
    popularity: 1.751,
    poster_path: '/yFI6AyrblDaTkJu3iYpZhdSp8wx.jpg',
    release_date: '1973-05-03',
    title: 'The Funny Face of the Godfather',
    video: false,
    vote_average: 2,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: '/7p0uo17fk1iXREkoRK6gQuCWxKy.jpg',
    genre_ids: [53, 28, 80],
    id: 261181,
    original_language: 'cn',
    original_title: '衝擊天子門生',
    overview:
      "When the boss of a highly profitable Triad family is forced to flee from Hong Kong, rival gangs swoop in to steal any piece of the action they can. York Koo (Andy Lau) becomes the family's acting boss, and must do what he can to handle the difficult situation, with mounting pressure from both the Hong Kong police, and rival families.",
    popularity: 2.21,
    poster_path: '/vk5qm3l8mV2xckuPV4mSplYhkcj.jpg',
    release_date: '1991-09-12',
    title: 'Hong Kong Godfather',
    video: false,
    vote_average: 9,
    vote_count: 1,
  },

  {
    adult: false,
    backdrop_path: '/u4YATs3X5PLcwCb4j4M6xJcgbty.jpg',
    genre_ids: [12, 10749, 18],
    id: 19666,
    original_language: 'hi',
    original_title: 'लगान',
    overview:
      'In 1890s India, an arrogant British commander challenges the harshly taxed residents of Champaner to a high-stakes cricket match.',
    popularity: 11.543,
    poster_path: '/yNX9lFRAFeNLNRIXdqZK9gYrYKa.jpg',
    release_date: '2001-06-15',
    title: 'Lagaan: Once Upon a Time in India',
    video: false,
    vote_average: 7.266,
    vote_count: 513,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 829332,
    original_language: 'en',
    original_title: 'Lagaan: The Thrill of Victory',
    overview:
      'Join Bhuvan and his team in a game of cricket against the British Raj from the superhit movie Lagaan. Set amidst an idyllic village and surrounded by rocky terrain and farms you get to be in the game with a motion simulator based ride that gives you the best point of view of a moving cricket ball.',
    popularity: 0.6,
    poster_path: '/jZQvD7w8fsNu8iNU24aNF0TuN7Q.jpg',
    release_date: '2016-11-17',
    title: 'Lagaan: The Thrill of Victory',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },

  {
    adult: false,
    backdrop_path: '/euCnMxNRlHNxA4f9BMnWbmxPOse.jpg',
    genre_ids: [10751, 16, 35],
    id: 20352,
    original_language: 'en',
    original_title: 'Despicable Me',
    overview:
      'Villainous Gru lives up to his reputation as a despicable, deplorable and downright unlikable guy when he hatches a plan to steal the moon from the sky. But he has a tough time staying on task after three orphans land in his care.',
    popularity: 57.966,
    poster_path: '/b1BT309QWjtFUlJPLmXmrcHOWEL.jpg',
    release_date: '2010-07-08',
    title: 'Despicable Me',
    video: false,
    vote_average: 7.23,
    vote_count: 14276,
  },
  {
    adult: false,
    backdrop_path: '/ftRkFtAGuHngHnLiOxktq0aCVMF.jpg',
    genre_ids: [28, 16, 35, 10751, 12],
    id: 324852,
    original_language: 'en',
    original_title: 'Despicable Me 3',
    overview:
      "Gru and his wife Lucy must stop former '80s child star Balthazar Bratt from achieving world domination.",
    popularity: 45.539,
    poster_path: '/6t3YWl7hrr88lCEFlGVqW5yV99R.jpg',
    release_date: '2017-06-15',
    title: 'Despicable Me 3',
    video: false,
    vote_average: 6.456,
    vote_count: 6637,
  },
  {
    adult: false,
    backdrop_path: '/fOipappvgVtUbbHOtmCkHzcwJjC.jpg',
    genre_ids: [16, 35, 10751],
    id: 93456,
    original_language: 'en',
    original_title: 'Despicable Me 2',
    overview:
      'Gru is recruited by the Anti-Villain League to help deal with a powerful new super criminal.',
    popularity: 59.632,
    poster_path: '/5Fh4NdoEnCjCK9wLjdJ9DJNFl2b.jpg',
    release_date: '2013-06-26',
    title: 'Despicable Me 2',
    video: false,
    vote_average: 6.919,
    vote_count: 10628,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [16, 10751, 35, 12],
    id: 519182,
    original_language: 'en',
    original_title: 'Despicable Me 4',
    overview: 'The fourth installment of the Despicable Me franchise.',
    popularity: 18.658,
    poster_path: '/vZeV20DxwjElUVjif5I3VhzMzqe.jpg',
    release_date: '2024-07-03',
    title: 'Despicable Me 4',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/cQ3tM5ueROE3s7nT86fmdjh5kvS.jpg',
    genre_ids: [10751, 12, 16, 35],
    id: 286558,
    original_language: 'en',
    original_title: 'Despicable Me Presents: Minion Madness',
    overview:
      'Three new mini-movies from the creators of Despicable Me. Orientation Day: Three freshly cloned minions go through the wacky orientation process at the evil laboratories of Gru. Home Makeover: The minions "assist" Edith, Margo & Agnes in a home makeover when they find out a social worker is going to pay them a visit. Watch the crazy antics ensue! Banana: A minion finds a banana in his lunch bag. To what lengths will the other minions go through to steal away that coveted yellow goodness?',
    popularity: 18.891,
    poster_path: '/smQcYI4DiF15HKt9RRpLywoWhnK.jpg',
    release_date: '2010-12-14',
    title: 'Despicable Me Presents: Minion Madness',
    video: true,
    vote_average: 6.864,
    vote_count: 158,
  },
  {
    adult: false,
    backdrop_path: '/7Dw4TjQkBlXAk3jG8duPfmPAGNr.jpg',
    genre_ids: [16],
    id: 326396,
    original_language: 'en',
    original_title: 'Despicable Me 2: 3 Mini-Movie Collection',
    overview:
      'Bringing laughs for the whole family, the mischievous Minions return in three new hilariously entertaining mini-movies. In "Puppy," when Kyle is unwilling to behave like a real dog, the Minions go looking for one who will. As usual, nothing goes as planned, and when their new friend gets homesick, it\'s time for some very creative thinking! "Panic In The Mailroom" is what happens when a suspicious package arrives and the Minions are totally unprepared. And in "Training Wheels," Agnes has some trouble with her bike and the Minions come to her aid - armed with a few helpful gadgets.',
    popularity: 11.125,
    poster_path: '/AoFxkze5c3JBkWm9zuAvulto2kv.jpg',
    release_date: '2014-10-24',
    title: 'Despicable Me 2: 3 Mini-Movie Collection',
    video: true,
    vote_average: 7.032,
    vote_count: 31,
  },
  {
    adult: false,
    backdrop_path: '/5a6fBXJS3TCol8IqA8tiSDvZGrQ.jpg',
    genre_ids: [35],
    id: 196864,
    original_language: 'fr',
    original_title: 'Mike Ward : Haïssable',
    overview:
      'After more than 200 shows, one Olivier and being put in default twice, Mike Ward offers you his latest standup show "Haïssable". Even those who thought they would hate it, loved it.',
    popularity: 0.639,
    poster_path: '/jULNUCJmTSW9VKAEXzFsQznDkzp.jpg',
    release_date: '2008-12-02',
    title: 'Mike Ward : Despicable',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 1079555,
    original_language: 'en',
    original_title: "Despicable Me 2: Gru's Girls",
    overview:
      'Miranda Cosgrove, Elsie Fisher and Dana Gaier on their roles in Despicable Me 2.',
    popularity: 1.422,
    poster_path: null,
    release_date: '',
    title: "Despicable Me 2: Gru's Girls",
    video: true,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 350551,
    original_language: 'en',
    original_title: 'Despicable Dick and Righteous Richard',
    overview:
      "Dick Kuchera has been pissing people off for 50 years. A recovering alcoholic from North Dakota, he finally musters the courage to complete the eighth and ninth steps of the 12-Step Program. With a list of everyone he's wronged -- from ex-wives to ex-mistresses, abandoned children to slighted pals -- Richard tries to make amends. But has he really changed?",
    popularity: 0.6,
    poster_path: null,
    release_date: '2011-01-01',
    title: 'Despicable Dick and Righteous Richard',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [],
    id: 1079554,
    original_language: 'en',
    original_title: 'Despicable Me 2: Gadgets Galore',
    overview: 'Gadgets from Despicable Me',
    popularity: 0.6,
    poster_path: null,
    release_date: '',
    title: 'Despicable Me 2: Gadgets Galore',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: '/c7xTZ9EA6GpH72xJC5s0x0KKR1a.jpg',
    genre_ids: [10751, 16, 12, 35],
    id: 211672,
    original_language: 'en',
    original_title: 'Minions',
    overview:
      'Minions Stuart, Kevin and Bob are recruited by Scarlet Overkill, a super-villain who, alongside her inventor husband Herb, hatches a plot to take over the world.',
    popularity: 27.525,
    poster_path: '/vlOgaxUiMOA8sPDG9n3VhQabnEi.jpg',
    release_date: '2015-06-17',
    title: 'Minions',
    video: false,
    vote_average: 6.399,
    vote_count: 10049,
  },
  {
    adult: false,
    backdrop_path: '/2Hckt3ug71qy1z9qrzHZx94pP0v.jpg',
    genre_ids: [16, 10751, 35],
    id: 54553,
    original_language: 'en',
    original_title: 'Minions: Home Makeover',
    overview:
      "A social worker is coming to Gru's house to check if it's suitable for children. Margo, Edith, Agnes and the Minions must take care of the situation.",
    popularity: 14.801,
    poster_path: '/c63xSHPgjE0BgoarcA97zq185SP.jpg',
    release_date: '2010-12-13',
    title: 'Minions: Home Makeover',
    video: false,
    vote_average: 6.709,
    vote_count: 163,
  },
  {
    adult: false,
    backdrop_path: '/fDjknkPghKnkFqqG268QEaW79X1.jpg',
    genre_ids: [16, 10751, 35],
    id: 54551,
    original_language: 'en',
    original_title: 'Banana',
    overview:
      'The Minions fight over a delicious banana... but is that all they want?!',
    popularity: 11.159,
    poster_path: '/AnmIMKAQjXLjD2DI0ba4D9DpkHv.jpg',
    release_date: '2010-12-13',
    title: 'Banana',
    video: false,
    vote_average: 7.103,
    vote_count: 262,
  },
  {
    adult: false,
    backdrop_path: '/vK48h2fZarnDjXdsnHZFyL5lveI.jpg',
    genre_ids: [16, 10751, 35, 878],
    id: 229407,
    original_language: 'en',
    original_title: 'Minions: Puppy',
    overview:
      'A Minion, seeing many owners walk their dogs, wants a puppy of his own. He tries to leash a ladybug but fails. Luckily, a UFO that sweeps away the ladybug somehow agrees to become a Puppy.',
    popularity: 8.391,
    poster_path: '/f62rLpyiebBc6QfSTA4xGwwQkPY.jpg',
    release_date: '2013-12-10',
    title: 'Minions: Puppy',
    video: false,
    vote_average: 7.12,
    vote_count: 208,
  },
  {
    adult: false,
    backdrop_path: '/rWXhj6vAVstbZdNRrgF8tAXrx1y.jpg',
    genre_ids: [16, 10751, 35],
    id: 54559,
    original_language: 'en',
    original_title: 'Minions: Orientation Day',
    overview:
      "With so many jobs to choose from, the Minions have to make serious decisions after watching an 'Initiation Video'. What could go wrong?!",
    popularity: 8.963,
    poster_path: '/bSTNLXAqkLmImXNcELrdCaew8dj.jpg',
    release_date: '2010-12-13',
    title: 'Minions: Orientation Day',
    video: false,
    vote_average: 6.829,
    vote_count: 178,
  },
  {
    adult: false,
    backdrop_path: '/wPgAh9xtJL10WcFy93uTqD6sl1l.jpg',
    genre_ids: [16, 35, 10751],
    id: 229408,
    original_language: 'en',
    original_title: 'Minions: Training Wheels',
    overview:
      'Margo, Edith, and Agnes spot an ice cream truck. The three of them go after the truck but Agnes falls as she attempts to pedal to the truck. The Minions, seeing her so upset by this, decide to build her a unicorn-themed motorcycle. Agnes goes for a little ride around town.',
    popularity: 9.823,
    poster_path: '/rT1L9N1LD2S1OO8qwzSFrphw0Oe.jpg',
    release_date: '2013-12-10',
    title: 'Minions: Training Wheels',
    video: false,
    vote_average: 6.938,
    vote_count: 169,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [16, 10751, 35, 878],
    id: 229405,
    original_language: 'en',
    original_title: 'Panic in the Mailroom',
    overview:
      'Two Minions are busy at work in the mailroom. One of them, bored, decides to throw a box of expired PX-41 samples into its designated chute.',
    popularity: 7.744,
    poster_path: '/xwZjM44xSQBhlQ55G1VCHKG5kC.jpg',
    release_date: '2013-12-10',
    title: 'Panic in the Mailroom',
    video: false,
    vote_average: 6.611,
    vote_count: 126,
  },
  {
    adult: false,
    backdrop_path: '/lOA8GjNcsE7QKfMrJMcBjNG6SJ3.jpg',
    genre_ids: [16, 35, 10751],
    id: 484809,
    original_language: 'en',
    original_title: 'The Secret Life of Kyle',
    overview:
      'After the events of Despicable Me 3, we follow Kyle and his secret life when Gru and his family are gone.',
    popularity: 5.784,
    poster_path: '/w5UR1ESmj0SGQgFLWlZ3G4UR3hc.jpg',
    release_date: '2017-08-02',
    title: 'The Secret Life of Kyle',
    video: false,
    vote_average: 5.759,
    vote_count: 29,
  },
];

// const simple_movies_array = movies.map(
//   ({
//     adult,
//     genre_ids,
//     original_language,
//     original_title,
//     popularity,
//     video,
//     vote_average,
//     vote_count,
//     ...rest
//   }) => rest
// );

export { movies };

console.log(movies.length);
